-- Bronze: brz_application_train
-- Fuente: application_train.csv
-- Filas: ~307,511 | Columnas: 122
-- Sin transformaciones - copia exacta del CSV fuente

USE hc_bronze;

DROP TABLE IF EXISTS brz_application_train;

CREATE TABLE brz_application_train (
    SK_ID_CURR                      INT             NOT NULL    COMMENT 'PK - ID del prestamo en la muestra',
    TARGET                          TINYINT         NULL        COMMENT 'Variable objetivo: 1=dificultad de pago, 0=sin problemas',
    NAME_CONTRACT_TYPE              VARCHAR(50)     NULL        COMMENT 'Tipo de contrato: Cash loans o Revolving loans',
    CODE_GENDER                     VARCHAR(5)      NULL        COMMENT 'Genero del cliente: M, F, XNA',
    FLAG_OWN_CAR                    VARCHAR(2)      NULL        COMMENT 'Tiene auto: Y/N',
    FLAG_OWN_REALTY                 VARCHAR(2)      NULL        COMMENT 'Tiene inmueble: Y/N',
    CNT_CHILDREN                    INT             NULL        COMMENT 'Numero de hijos',
    AMT_INCOME_TOTAL                DECIMAL(15,2)   NULL        COMMENT 'Ingreso total anual del cliente',
    AMT_CREDIT                      DECIMAL(15,2)   NULL        COMMENT 'Monto total del credito',
    AMT_ANNUITY                     DECIMAL(15,2)   NULL        COMMENT 'Cuota anual del prestamo',
    AMT_GOODS_PRICE                 DECIMAL(15,2)   NULL        COMMENT 'Precio del bien para creditos de consumo',
    NAME_TYPE_SUITE                 VARCHAR(50)     NULL        COMMENT 'Quien acompano al cliente al solicitar',
    NAME_INCOME_TYPE                VARCHAR(50)     NULL        COMMENT 'Tipo de ingreso del cliente',
    NAME_EDUCATION_TYPE             VARCHAR(50)     NULL        COMMENT 'Nivel educativo del cliente',
    NAME_FAMILY_STATUS              VARCHAR(50)     NULL        COMMENT 'Estado civil del cliente',
    NAME_HOUSING_TYPE               VARCHAR(50)     NULL        COMMENT 'Situacion habitacional del cliente',
    REGION_POPULATION_RELATIVE      FLOAT           NULL        COMMENT 'Poblacion normalizada de la region',
    DAYS_BIRTH                      INT             NULL        COMMENT 'Edad en dias (negativo) al momento de la solicitud',
    DAYS_EMPLOYED                   INT             NULL        COMMENT 'Dias de empleo actual (negativo). 365243=jubilado/sin empleo',
    DAYS_REGISTRATION               FLOAT           NULL        COMMENT 'Dias desde cambio de registro',
    DAYS_ID_PUBLISH                 INT             NULL        COMMENT 'Dias desde cambio de documento de identidad',
    OWN_CAR_AGE                     FLOAT           NULL        COMMENT 'Edad del auto del cliente',
    FLAG_MOBIL                      TINYINT         NULL        COMMENT 'Proporciono telefono movil: 1/0',
    FLAG_EMP_PHONE                  TINYINT         NULL        COMMENT 'Proporciono telefono laboral: 1/0',
    FLAG_WORK_PHONE                 TINYINT         NULL        COMMENT 'Proporciono telefono de trabajo: 1/0',
    FLAG_CONT_MOBILE                TINYINT         NULL        COMMENT 'Telefono movil accesible: 1/0',
    FLAG_PHONE                      TINYINT         NULL        COMMENT 'Proporciono telefono fijo: 1/0',
    FLAG_EMAIL                      TINYINT         NULL        COMMENT 'Proporciono email: 1/0',
    OCCUPATION_TYPE                 VARCHAR(50)     NULL        COMMENT 'Tipo de ocupacion del cliente',
    CNT_FAM_MEMBERS                 FLOAT           NULL        COMMENT 'Numero de miembros familiares',
    REGION_RATING_CLIENT            INT             NULL        COMMENT 'Rating de la region del cliente (1,2,3)',
    REGION_RATING_CLIENT_W_CITY     INT             NULL        COMMENT 'Rating de la region incluyendo ciudad (1,2,3)',
    WEEKDAY_APPR_PROCESS_START      VARCHAR(15)     NULL        COMMENT 'Dia de la semana de la solicitud',
    HOUR_APPR_PROCESS_START         INT             NULL        COMMENT 'Hora aproximada de la solicitud',
    REG_REGION_NOT_LIVE_REGION      TINYINT         NULL        COMMENT 'Direccion permanente difiere de contacto (region)',
    REG_REGION_NOT_WORK_REGION      TINYINT         NULL        COMMENT 'Direccion permanente difiere de trabajo (region)',
    LIVE_REGION_NOT_WORK_REGION     TINYINT         NULL        COMMENT 'Direccion contacto difiere de trabajo (region)',
    REG_CITY_NOT_LIVE_CITY          TINYINT         NULL        COMMENT 'Direccion permanente difiere de contacto (ciudad)',
    REG_CITY_NOT_WORK_CITY          TINYINT         NULL        COMMENT 'Direccion permanente difiere de trabajo (ciudad)',
    LIVE_CITY_NOT_WORK_CITY         TINYINT         NULL        COMMENT 'Direccion contacto difiere de trabajo (ciudad)',
    ORGANIZATION_TYPE               VARCHAR(100)    NULL        COMMENT 'Tipo de organizacion donde trabaja el cliente',
    EXT_SOURCE_1                    FLOAT           NULL        COMMENT 'Score normalizado fuente externa 1 - alta predictividad',
    EXT_SOURCE_2                    FLOAT           NULL        COMMENT 'Score normalizado fuente externa 2 - alta predictividad',
    EXT_SOURCE_3                    FLOAT           NULL        COMMENT 'Score normalizado fuente externa 3 - alta predictividad',
    APARTMENTS_AVG                  FLOAT           NULL        COMMENT 'Tamano promedio apartamento normalizado',
    BASEMENTAREA_AVG                FLOAT           NULL        COMMENT 'Area sotano promedio normalizado',
    YEARS_BEGINEXPLUATATION_AVG     FLOAT           NULL        COMMENT 'Anos inicio explotacion edificio promedio',
    YEARS_BUILD_AVG                 FLOAT           NULL        COMMENT 'Ano construccion edificio promedio',
    COMMONAREA_AVG                  FLOAT           NULL        COMMENT 'Area comun promedio normalizado',
    ELEVATORS_AVG                   FLOAT           NULL        COMMENT 'Numero elevadores promedio',
    ENTRANCES_AVG                   FLOAT           NULL        COMMENT 'Numero entradas promedio',
    FLOORSMAX_AVG                   FLOAT           NULL        COMMENT 'Pisos maximos promedio',
    FLOORSMIN_AVG                   FLOAT           NULL        COMMENT 'Pisos minimos promedio',
    LANDAREA_AVG                    FLOAT           NULL        COMMENT 'Area terreno promedio normalizado',
    LIVINGAPARTMENTS_AVG            FLOAT           NULL        COMMENT 'Apartamentos habitables promedio',
    LIVINGAREA_AVG                  FLOAT           NULL        COMMENT 'Area habitable promedio normalizado',
    NONLIVINGAPARTMENTS_AVG         FLOAT           NULL        COMMENT 'Apartamentos no habitables promedio',
    NONLIVINGAREA_AVG               FLOAT           NULL        COMMENT 'Area no habitable promedio normalizado',
    APARTMENTS_MODE                 FLOAT           NULL        COMMENT 'Tamano apartamento moda',
    BASEMENTAREA_MODE               FLOAT           NULL        COMMENT 'Area sotano moda',
    YEARS_BEGINEXPLUATATION_MODE    FLOAT           NULL        COMMENT 'Anos inicio explotacion moda',
    YEARS_BUILD_MODE                FLOAT           NULL        COMMENT 'Ano construccion moda',
    COMMONAREA_MODE                 FLOAT           NULL        COMMENT 'Area comun moda',
    ELEVATORS_MODE                  FLOAT           NULL        COMMENT 'Elevadores moda',
    ENTRANCES_MODE                  FLOAT           NULL        COMMENT 'Entradas moda',
    FLOORSMAX_MODE                  FLOAT           NULL        COMMENT 'Pisos maximos moda',
    FLOORSMIN_MODE                  FLOAT           NULL        COMMENT 'Pisos minimos moda',
    LANDAREA_MODE                   FLOAT           NULL        COMMENT 'Area terreno moda',
    LIVINGAPARTMENTS_MODE           FLOAT           NULL        COMMENT 'Apartamentos habitables moda',
    LIVINGAREA_MODE                 FLOAT           NULL        COMMENT 'Area habitable moda',
    NONLIVINGAPARTMENTS_MODE        FLOAT           NULL        COMMENT 'Apartamentos no habitables moda',
    NONLIVINGAREA_MODE              FLOAT           NULL        COMMENT 'Area no habitable moda',
    APARTMENTS_MEDI                 FLOAT           NULL        COMMENT 'Tamano apartamento mediana',
    BASEMENTAREA_MEDI               FLOAT           NULL        COMMENT 'Area sotano mediana',
    YEARS_BEGINEXPLUATATION_MEDI    FLOAT           NULL        COMMENT 'Anos inicio explotacion mediana',
    YEARS_BUILD_MEDI                FLOAT           NULL        COMMENT 'Ano construccion mediana',
    COMMONAREA_MEDI                 FLOAT           NULL        COMMENT 'Area comun mediana',
    ELEVATORS_MEDI                  FLOAT           NULL        COMMENT 'Elevadores mediana',
    ENTRANCES_MEDI                  FLOAT           NULL        COMMENT 'Entradas mediana',
    FLOORSMAX_MEDI                  FLOAT           NULL        COMMENT 'Pisos maximos mediana',
    FLOORSMIN_MEDI                  FLOAT           NULL        COMMENT 'Pisos minimos mediana',
    LANDAREA_MEDI                   FLOAT           NULL        COMMENT 'Area terreno mediana',
    LIVINGAPARTMENTS_MEDI           FLOAT           NULL        COMMENT 'Apartamentos habitables mediana',
    LIVINGAREA_MEDI                 FLOAT           NULL        COMMENT 'Area habitable mediana',
    NONLIVINGAPARTMENTS_MEDI        FLOAT           NULL        COMMENT 'Apartamentos no habitables mediana',
    NONLIVINGAREA_MEDI              FLOAT           NULL        COMMENT 'Area no habitable mediana',
    FONDKAPREMONT_MODE              VARCHAR(50)     NULL        COMMENT 'Fondo reparacion edificio moda',
    HOUSETYPE_MODE                  VARCHAR(50)     NULL        COMMENT 'Tipo de casa moda',
    TOTALAREA_MODE                  FLOAT           NULL        COMMENT 'Area total moda',
    WALLSMATERIAL_MODE              VARCHAR(50)     NULL        COMMENT 'Material paredes moda',
    EMERGENCYSTATE_MODE             VARCHAR(10)     NULL        COMMENT 'Estado emergencia edificio moda',
    OBS_30_CNT_SOCIAL_CIRCLE        FLOAT           NULL        COMMENT 'Observaciones entorno social con 30 DPD',
    DEF_30_CNT_SOCIAL_CIRCLE        FLOAT           NULL        COMMENT 'Defaults entorno social con 30 DPD',
    OBS_60_CNT_SOCIAL_CIRCLE        FLOAT           NULL        COMMENT 'Observaciones entorno social con 60 DPD',
    DEF_60_CNT_SOCIAL_CIRCLE        FLOAT           NULL        COMMENT 'Defaults entorno social con 60 DPD',
    DAYS_LAST_PHONE_CHANGE          FLOAT           NULL        COMMENT 'Dias desde cambio de telefono',
    FLAG_DOCUMENT_2                 TINYINT         NULL        COMMENT 'Proporciono documento 2',
    FLAG_DOCUMENT_3                 TINYINT         NULL        COMMENT 'Proporciono documento 3',
    FLAG_DOCUMENT_4                 TINYINT         NULL        COMMENT 'Proporciono documento 4',
    FLAG_DOCUMENT_5                 TINYINT         NULL        COMMENT 'Proporciono documento 5',
    FLAG_DOCUMENT_6                 TINYINT         NULL        COMMENT 'Proporciono documento 6',
    FLAG_DOCUMENT_7                 TINYINT         NULL        COMMENT 'Proporciono documento 7',
    FLAG_DOCUMENT_8                 TINYINT         NULL        COMMENT 'Proporciono documento 8',
    FLAG_DOCUMENT_9                 TINYINT         NULL        COMMENT 'Proporciono documento 9',
    FLAG_DOCUMENT_10                TINYINT         NULL        COMMENT 'Proporciono documento 10',
    FLAG_DOCUMENT_11                TINYINT         NULL        COMMENT 'Proporciono documento 11',
    FLAG_DOCUMENT_12                TINYINT         NULL        COMMENT 'Proporciono documento 12',
    FLAG_DOCUMENT_13                TINYINT         NULL        COMMENT 'Proporciono documento 13',
    FLAG_DOCUMENT_14                TINYINT         NULL        COMMENT 'Proporciono documento 14',
    FLAG_DOCUMENT_15                TINYINT         NULL        COMMENT 'Proporciono documento 15',
    FLAG_DOCUMENT_16                TINYINT         NULL        COMMENT 'Proporciono documento 16',
    FLAG_DOCUMENT_17                TINYINT         NULL        COMMENT 'Proporciono documento 17',
    FLAG_DOCUMENT_18                TINYINT         NULL        COMMENT 'Proporciono documento 18',
    FLAG_DOCUMENT_19                TINYINT         NULL        COMMENT 'Proporciono documento 19',
    FLAG_DOCUMENT_20                TINYINT         NULL        COMMENT 'Proporciono documento 20',
    FLAG_DOCUMENT_21                TINYINT         NULL        COMMENT 'Proporciono documento 21',
    AMT_REQ_CREDIT_BUREAU_HOUR      FLOAT           NULL        COMMENT 'Consultas al buro 1 hora antes',
    AMT_REQ_CREDIT_BUREAU_DAY       FLOAT           NULL        COMMENT 'Consultas al buro 1 dia antes',
    AMT_REQ_CREDIT_BUREAU_WEEK      FLOAT           NULL        COMMENT 'Consultas al buro 1 semana antes',
    AMT_REQ_CREDIT_BUREAU_MON       FLOAT           NULL        COMMENT 'Consultas al buro 1 mes antes',
    AMT_REQ_CREDIT_BUREAU_QRT       FLOAT           NULL        COMMENT 'Consultas al buro 3 meses antes',
    AMT_REQ_CREDIT_BUREAU_YEAR      FLOAT           NULL        COMMENT 'Consultas al buro 1 ano antes',
    _ingested_at                    TIMESTAMP       NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp de carga a Bronze',
    _source_file                    VARCHAR(100)    NOT NULL    DEFAULT 'application_train.csv' COMMENT 'Archivo CSV de origen',
    PRIMARY KEY (SK_ID_CURR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Bronze: copia exacta de application_train.csv';