-- Bronze: brz_application_test
-- Fuente: application_test.csv
-- Filas: ~48,744 | Columnas: 122
-- Misma estructura que application_train sin columna TARGET

USE hc_bronze;

DROP TABLE IF EXISTS brz_application_test;

CREATE TABLE brz_application_test (
    SK_ID_CURR                      INT             NOT NULL    COMMENT 'PK - ID del prestamo en la muestra',
    NAME_CONTRACT_TYPE              VARCHAR(50)     NULL        COMMENT 'Tipo de contrato',
    CODE_GENDER                     VARCHAR(5)      NULL        COMMENT 'Genero del cliente',
    FLAG_OWN_CAR                    VARCHAR(2)      NULL        COMMENT 'Tiene auto: Y/N',
    FLAG_OWN_REALTY                 VARCHAR(2)      NULL        COMMENT 'Tiene inmueble: Y/N',
    CNT_CHILDREN                    INT             NULL        COMMENT 'Numero de hijos',
    AMT_INCOME_TOTAL                DECIMAL(15,2)   NULL        COMMENT 'Ingreso total anual',
    AMT_CREDIT                      DECIMAL(15,2)   NULL        COMMENT 'Monto total del credito',
    AMT_ANNUITY                     DECIMAL(15,2)   NULL        COMMENT 'Cuota anual',
    AMT_GOODS_PRICE                 DECIMAL(15,2)   NULL        COMMENT 'Precio del bien',
    NAME_TYPE_SUITE                 VARCHAR(50)     NULL        COMMENT 'Quien acompano al cliente',
    NAME_INCOME_TYPE                VARCHAR(50)     NULL        COMMENT 'Tipo de ingreso',
    NAME_EDUCATION_TYPE             VARCHAR(50)     NULL        COMMENT 'Nivel educativo',
    NAME_FAMILY_STATUS              VARCHAR(50)     NULL        COMMENT 'Estado civil',
    NAME_HOUSING_TYPE               VARCHAR(50)     NULL        COMMENT 'Situacion habitacional',
    REGION_POPULATION_RELATIVE      FLOAT           NULL        COMMENT 'Poblacion normalizada de la region',
    DAYS_BIRTH                      INT             NULL        COMMENT 'Edad en dias (negativo)',
    DAYS_EMPLOYED                   INT             NULL        COMMENT 'Dias de empleo actual. 365243=jubilado',
    DAYS_REGISTRATION               FLOAT           NULL        COMMENT 'Dias desde cambio de registro',
    DAYS_ID_PUBLISH                 INT             NULL        COMMENT 'Dias desde cambio de documento',
    OWN_CAR_AGE                     FLOAT           NULL        COMMENT 'Edad del auto',
    FLAG_MOBIL                      TINYINT         NULL        COMMENT 'Proporciono movil: 1/0',
    FLAG_EMP_PHONE                  TINYINT         NULL        COMMENT 'Proporciono tel laboral: 1/0',
    FLAG_WORK_PHONE                 TINYINT         NULL        COMMENT 'Proporciono tel trabajo: 1/0',
    FLAG_CONT_MOBILE                TINYINT         NULL        COMMENT 'Movil accesible: 1/0',
    FLAG_PHONE                      TINYINT         NULL        COMMENT 'Proporciono tel fijo: 1/0',
    FLAG_EMAIL                      TINYINT         NULL        COMMENT 'Proporciono email: 1/0',
    OCCUPATION_TYPE                 VARCHAR(50)     NULL        COMMENT 'Tipo de ocupacion',
    CNT_FAM_MEMBERS                 FLOAT           NULL        COMMENT 'Miembros familiares',
    REGION_RATING_CLIENT            INT             NULL        COMMENT 'Rating region (1,2,3)',
    REGION_RATING_CLIENT_W_CITY     INT             NULL        COMMENT 'Rating region con ciudad (1,2,3)',
    WEEKDAY_APPR_PROCESS_START      VARCHAR(15)     NULL        COMMENT 'Dia de la semana de solicitud',
    HOUR_APPR_PROCESS_START         INT             NULL        COMMENT 'Hora de solicitud',
    REG_REGION_NOT_LIVE_REGION      TINYINT         NULL        COMMENT 'Direccion difiere contacto (region)',
    REG_REGION_NOT_WORK_REGION      TINYINT         NULL        COMMENT 'Direccion difiere trabajo (region)',
    LIVE_REGION_NOT_WORK_REGION     TINYINT         NULL        COMMENT 'Contacto difiere trabajo (region)',
    REG_CITY_NOT_LIVE_CITY          TINYINT         NULL        COMMENT 'Direccion difiere contacto (ciudad)',
    REG_CITY_NOT_WORK_CITY          TINYINT         NULL        COMMENT 'Direccion difiere trabajo (ciudad)',
    LIVE_CITY_NOT_WORK_CITY         TINYINT         NULL        COMMENT 'Contacto difiere trabajo (ciudad)',
    ORGANIZATION_TYPE               VARCHAR(100)    NULL        COMMENT 'Tipo de organizacion empleadora',
    EXT_SOURCE_1                    FLOAT           NULL        COMMENT 'Score externo 1',
    EXT_SOURCE_2                    FLOAT           NULL        COMMENT 'Score externo 2',
    EXT_SOURCE_3                    FLOAT           NULL        COMMENT 'Score externo 3',
    APARTMENTS_AVG                  FLOAT           NULL,
    BASEMENTAREA_AVG                FLOAT           NULL,
    YEARS_BEGINEXPLUATATION_AVG     FLOAT           NULL,
    YEARS_BUILD_AVG                 FLOAT           NULL,
    COMMONAREA_AVG                  FLOAT           NULL,
    ELEVATORS_AVG                   FLOAT           NULL,
    ENTRANCES_AVG                   FLOAT           NULL,
    FLOORSMAX_AVG                   FLOAT           NULL,
    FLOORSMIN_AVG                   FLOAT           NULL,
    LANDAREA_AVG                    FLOAT           NULL,
    LIVINGAPARTMENTS_AVG            FLOAT           NULL,
    LIVINGAREA_AVG                  FLOAT           NULL,
    NONLIVINGAPARTMENTS_AVG         FLOAT           NULL,
    NONLIVINGAREA_AVG               FLOAT           NULL,
    APARTMENTS_MODE                 FLOAT           NULL,
    BASEMENTAREA_MODE               FLOAT           NULL,
    YEARS_BEGINEXPLUATATION_MODE    FLOAT           NULL,
    YEARS_BUILD_MODE                FLOAT           NULL,
    COMMONAREA_MODE                 FLOAT           NULL,
    ELEVATORS_MODE                  FLOAT           NULL,
    ENTRANCES_MODE                  FLOAT           NULL,
    FLOORSMAX_MODE                  FLOAT           NULL,
    FLOORSMIN_MODE                  FLOAT           NULL,
    LANDAREA_MODE                   FLOAT           NULL,
    LIVINGAPARTMENTS_MODE           FLOAT           NULL,
    LIVINGAREA_MODE                 FLOAT           NULL,
    NONLIVINGAPARTMENTS_MODE        FLOAT           NULL,
    NONLIVINGAREA_MODE              FLOAT           NULL,
    APARTMENTS_MEDI                 FLOAT           NULL,
    BASEMENTAREA_MEDI               FLOAT           NULL,
    YEARS_BEGINEXPLUATATION_MEDI    FLOAT           NULL,
    YEARS_BUILD_MEDI                FLOAT           NULL,
    COMMONAREA_MEDI                 FLOAT           NULL,
    ELEVATORS_MEDI                  FLOAT           NULL,
    ENTRANCES_MEDI                  FLOAT           NULL,
    FLOORSMAX_MEDI                  FLOAT           NULL,
    FLOORSMIN_MEDI                  FLOAT           NULL,
    LANDAREA_MEDI                   FLOAT           NULL,
    LIVINGAPARTMENTS_MEDI           FLOAT           NULL,
    LIVINGAREA_MEDI                 FLOAT           NULL,
    NONLIVINGAPARTMENTS_MEDI        FLOAT           NULL,
    NONLIVINGAREA_MEDI              FLOAT           NULL,
    FONDKAPREMONT_MODE              VARCHAR(50)     NULL,
    HOUSETYPE_MODE                  VARCHAR(50)     NULL,
    TOTALAREA_MODE                  FLOAT           NULL,
    WALLSMATERIAL_MODE              VARCHAR(50)     NULL,
    EMERGENCYSTATE_MODE             VARCHAR(10)     NULL,
    OBS_30_CNT_SOCIAL_CIRCLE        FLOAT           NULL,
    DEF_30_CNT_SOCIAL_CIRCLE        FLOAT           NULL,
    OBS_60_CNT_SOCIAL_CIRCLE        FLOAT           NULL,
    DEF_60_CNT_SOCIAL_CIRCLE        FLOAT           NULL,
    DAYS_LAST_PHONE_CHANGE          FLOAT           NULL,
    FLAG_DOCUMENT_2                 TINYINT         NULL,
    FLAG_DOCUMENT_3                 TINYINT         NULL,
    FLAG_DOCUMENT_4                 TINYINT         NULL,
    FLAG_DOCUMENT_5                 TINYINT         NULL,
    FLAG_DOCUMENT_6                 TINYINT         NULL,
    FLAG_DOCUMENT_7                 TINYINT         NULL,
    FLAG_DOCUMENT_8                 TINYINT         NULL,
    FLAG_DOCUMENT_9                 TINYINT         NULL,
    FLAG_DOCUMENT_10                TINYINT         NULL,
    FLAG_DOCUMENT_11                TINYINT         NULL,
    FLAG_DOCUMENT_12                TINYINT         NULL,
    FLAG_DOCUMENT_13                TINYINT         NULL,
    FLAG_DOCUMENT_14                TINYINT         NULL,
    FLAG_DOCUMENT_15                TINYINT         NULL,
    FLAG_DOCUMENT_16                TINYINT         NULL,
    FLAG_DOCUMENT_17                TINYINT         NULL,
    FLAG_DOCUMENT_18                TINYINT         NULL,
    FLAG_DOCUMENT_19                TINYINT         NULL,
    FLAG_DOCUMENT_20                TINYINT         NULL,
    FLAG_DOCUMENT_21                TINYINT         NULL,
    AMT_REQ_CREDIT_BUREAU_HOUR      FLOAT           NULL,
    AMT_REQ_CREDIT_BUREAU_DAY       FLOAT           NULL,
    AMT_REQ_CREDIT_BUREAU_WEEK      FLOAT           NULL,
    AMT_REQ_CREDIT_BUREAU_MON       FLOAT           NULL,
    AMT_REQ_CREDIT_BUREAU_QRT       FLOAT           NULL,
    AMT_REQ_CREDIT_BUREAU_YEAR      FLOAT           NULL,
    _ingested_at                    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp de carga a Bronze',
    _source_file                    VARCHAR(100)    NOT NULL DEFAULT 'application_test.csv' COMMENT 'Archivo CSV de origen',
    PRIMARY KEY (SK_ID_CURR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Bronze: copia exacta de application_test.csv';